### ISSUE TITLE
crash 1.21.1 fabric

### ISSUE THREAD

**Issue by NeoFolia** [rotgruengelb/MyNethersDelightRefabricated#5] opened 2024-11-28 04:51 UTC
[crash-2024-11-28_07.23.57-client.txt](https://github.com/user-attachments/files/17942823/crash-2024-11-28_07.23.57-client.txt)

**Comment by ChrysanthCow** [comment] 2024-12-03 22:04
Duplicate of #7

**Closed as completed by ChrysanthCow** 2024-12-03 22:04 UTC
